name: Deploy Dashboard via NerdGraph

on:
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      ACCOUNT_IDS: ${{ secrets.ACCOUNT_IDS }}  # Comma-separated list like: 12345,67890

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace placeholders in template
        run: |
          mkdir -p rendered
          sed "s/{{ACCOUNT_ID}}/${ACCOUNT_ID}/g; s/{{ACCOUNT_IDS}}/${ACCOUNT_IDS}/g" templates/dashboard_template.json > rendered/dashboard.json

      - name: Create GraphQL payload
        run: |
          DASHBOARD=$(jq . rendered/dashboard.json)
          ACCOUNT_ID_INT=$(echo "$ACCOUNT_ID" | jq -r '. | tonumber')

          echo "{
            \"query\": \"mutation CreateDashboard(\$accountId: Int!, \$dashboard: DashboardInput!) {
              dashboardCreate(accountId: \$accountId, dashboard: \$dashboard) {
                entityResult { guid }
                errors { description }
              }
            }\",
            \"variables\": {
              \"accountId\": $ACCOUNT_ID_INT,
              \"dashboard\": $DASHBOARD
            }
          }" > rendered/payload.json

      - name: Deploy to New Relic via NerdGraph
        run: |
          echo "🚀 Deploying dashboard to New Relic NerdGraph..."
          curl --request POST \
            --url https://api.newrelic.com/graphql \
            --header "Content-Type: application/json" \
            --header "API-Key: $API_KEY" \
            --data @rendered/payload.json
