name: Deploy Dashboard via NerdGraph

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'customer/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace placeholders in template
        run: |
          mkdir -p rendered
          sed "s/{{ACCOUNT_ID}}/${ACCOUNT_ID}/g" templates/dashboard_template.json > rendered/tmp.json

      - name: Build NerdGraph mutation
        run: |
          DASHBOARD_JSON=$(jq -c '.' < rendered/tmp.json)

          echo "{\"query\":\"mutation { dashboardCreate(accountId: ${ACCOUNT_ID}, dashboard: ${DASHBOARD_JSON//\"/\\\"}) { entityResult { guid } errors { description } } }\"}" > rendered/payload.json

      - name: Deploy via NerdGraph
        run: |
          curl --request POST \
            --url https://api.newrelic.com/graphql \
            --header "Content-Type: application/json" \
            --header "API-Key: $API_KEY" \
            --data @rendered/payload.json
