name: Deploy Dashboard to New Relic

on:
  workflow_dispatch:  # ✅ Enables manual run with branch selection
  push:
    branches:
      - main
      - 'customer/**'  # ✅ So it also runs automatically on customer branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace placeholders in template
        run: |
          mkdir -p rendered
          cat templates/dashboard_template.json \
          | sed "s/{{ACCOUNT_ID}}/${ACCOUNT_ID}/g" \
          > rendered/dashboard.json

      - name: Deploy dashboard to New Relic
        run: |
          curl --request POST \
            --url https://api.newrelic.com/v2/dashboards.json \
            --header "X-Api-Key: $API_KEY" \
            --header "Content-Type: application/json" \
            --data @rendered/dashboard.json
