name: Deploy Dashboard via NerdGraph

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'customer/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace placeholders in template
        run: |
          mkdir -p rendered
          sed "s/{{ACCOUNT_ID}}/${ACCOUNT_ID}/g" templates/dashboard_template.json > rendered/dashboard.json

      - name: Create GraphQL payload using variables
        run: |
          DASHBOARD=$(cat rendered/dashboard.json | jq .)
          ACCOUNT_ID_INT=$(echo "$ACCOUNT_ID" | jq -r '. | tonumber')

          cat > rendered/payload.json <<EOF
{
  "query": "mutation CreateDashboard(\$accountId: Int!, \$dashboard: DashboardInput!) { dashboardCreate(accountId: \$accountId, dashboard: \$dashboard) { entityResult { guid } errors { description } } }",
  "variables": {
    "accountId": $ACCOUNT_ID_INT,
    "dashboard": $DASHBOARD
  }
}
EOF

      - name: Deploy to New Relic via NerdGraph
        run: |
          echo "🚀 Deploying dashboard..."
          curl --request POST \
            --url https://api.newrelic.com/graphql \
            --header "Content-Type: application/json" \
            --header "API-Key: $API_KEY" \
            --data @rendered/payload.json
