name: Deploy Dashboard to New Relic

on:
  workflow_dispatch:  # ✅ Enables manual trigger with branch selection
  push:
    branches:
      - main
      - 'customer/**'  # ✅ Auto-run for any customer branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace placeholders and wrap in dashboard object
        run: |
          mkdir -p rendered

          # Replace {{ACCOUNT_ID}} in the template and wrap it
          sed "s/{{ACCOUNT_ID}}/${ACCOUNT_ID}/g" templates/dashboard_template.json > rendered/tmp.json

          # Wrap the entire result in a "dashboard" object
          echo "{\"dashboard\":$(cat rendered/tmp.json)}" > rendered/dashboard.json

      - name: Deploy dashboard to New Relic
        run: |
          curl --request POST \
            --url https://api.newrelic.com/v2/dashboards.json \
            --header "X-Api-Key: $API_KEY" \
            --header "Content-Type: application/json" \
            --data @rendered/dashboard.json
