name: Deploy Dashboard via NerdGraph

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'customer/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace placeholders in template
        run: |
          mkdir -p rendered
          sed "s/{{ACCOUNT_ID}}/${ACCOUNT_ID}/g" templates/dashboard_template.json > rendered/dashboard.json

      - name: Build NerdGraph mutation
        run: |
          RAW_JSON=$(cat rendered/dashboard.json)

          # Compose raw GraphQL mutation string
          MUTATION="mutation {
            dashboardCreate(accountId: ${ACCOUNT_ID}, dashboard: ${RAW_JSON}) {
              entityResult { guid }
              errors { description }
            }
          }"

          # Convert raw string into escaped JSON payload using jq
          echo "{\"query\": $(jq -Rs . <<< \"$MUTATION\") }" > rendered/payload.json

      - name: Deploy via NerdGraph
        run: |
          curl --request POST \
            --url https://api.newrelic.com/graphql \
            --header "Content-Type: application/json" \
            --header "API-Key: $API_KEY" \
            --data @rendered/payload.json
