name: Deploy Dashboard via NerdGraph

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'customer/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build NerdGraph mutation
        run: |
          mkdir -p rendered

          # Replace placeholders
          sed "s/{{ACCOUNT_ID}}/${ACCOUNT_ID}/g" templates/dashboard_template.json > rendered/tmp.json

          # Escape the JSON so it can be used inside GraphQL
          DASHBOARD_JSON=$(cat rendered/tmp.json | jq -c '.')

          # Create the final GraphQL payload
          cat <<EOF > rendered/payload.json
{
  "query": "mutation { dashboardCreate(accountId: ${ACCOUNT_ID}, dashboard: ${DASHBOARD_JSON}) { entityResult { guid } errors { description } } }"
}
EOF

      - name: Deploy via NerdGraph
        run: |
          curl --request POST \
            --url https://api.newrelic.com/graphql \
            --header "Content-Type: application/json" \
            --header "API-Key: $API_KEY" \
            --data @rendered/payload.json
